#!/usr/bin/env python3
"""
Carpet Fishing. Inspired by dilbert.
"""
import argparse
from time import sleep
from random import randrange, choice

# Possible Catches

# Parse Arguements
parser = argparse.ArgumentParser()
parser.add_argument('-s', '--spots', dest='spots', type=int, default=9,
					help='Number of fishing holes')
parser.add_argument('-sq', '--square', dest='square', type=bool, nargs='?', const=True, default=False,
					help='Treats spots as the side of a square, i.e. (X,Y).')
parser.add_argument('-r', '--rate', dest='rate', type=int, default=3600,
					help='Average time between catches')
parser.add_argument('-c', '--catches', dest='maxCatches', type=int, default=0,
					help='Number of fish to find')
args = parser.parse_args()


# Cast a line
print('\nCast your line!\n')

def catch(size, isSquare):
	fishlist = ['Marlin', 'Bass', 'Trout',
	            'Salmon', 'Flounder', 'Catfish',
	            'Bluegill', 'Grouper', 'Cod',
	            'Red Snapper']
	f = choice(fishlist)
	if isSquare:
		l = '(' + str(randrange(1,size+1)) + ',' + str(randrange(1,size+1)) + ')'
	else:
		l = str(randrange(1,size+1))
	return (f, l)
# Loop
i = 0
while args.maxCatches == 0 or i < args.maxCatches:
	sleep(args.rate)
	c = catch(args.spots, args.square)
	print('There\'s a', c[0], 'in spot', c[1])
	i += 1
